In [16]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr[1,2])
print('next')

print(arr[0,:2])
print('next') 
      
print(arr[:,1])
print('next')  

print(arr[1,:])
print('next')

[[1 2 3]
 [4 5 6]]
6
next
[1 2]
next
[2 5]
next
[4 5 6]
next


In [20]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

print(a+b)

print(a-b)

print(a*b)

print(a ** b)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]


In [22]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

2
(2, 3)
6
int32
4


In [24]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b.sum)
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min())
print(b.max())
print(b.mean())
print(b.std())

<built-in method sum of numpy.ndarray object at 0x0000025AE4643AB0>
[5 7 9]
[ 6 15]
1
6
3.5
1.707825127659933


In [28]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))
print(np.transpose(a))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [32]:
import numpy as np
a = np.array([1,2,3,4])
for index_value,value in enumerate(a):
    print(f'this is index value{index_value} and value of data{value}')

this is index value0 and value of data1
this is index value1 and value of data2
this is index value2 and value of data3
this is index value3 and value of data4
