In [1]:
# Real World Expense Tracker using NumPy
import numpy as np
categories = ['health', 'transport', 'groceries']
expenses = np.array([
    [2500, 3000, 2000],  
    [2500, 2800, 2200],  
    [2700, 2600, 2000]  
])

print("Expenses Array:")
print(expenses)

total_per_category = expenses.sum(axis=0)

print("\nTotal per Category:")
for i, category in enumerate(categories):
    print(f"{category}: {total_per_category[i]}")

total_expenses = total_per_category.sum()
print(f"\nOverall Total Expenses: {total_expenses}")

average_monthly_expense = expenses.mean()
print(f"Average Monthly Expense: {average_monthly_expense:.2f}")


Expenses Array:
[[2500 3000 2000]
 [2500 2800 2200]
 [2700 2600 2000]]

Total per Category:
health: 7700
transport: 8400
groceries: 6200

Overall Total Expenses: 22300
Average Monthly Expense: 2477.78
